version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: valkey/valkey:8.0.1-alpine
    restart: unless-stopped
