version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis
    restart: unless-stopped
