version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis
    restart: unless-stopped
